# ------ APT Packages ------
apt_packages:
  - apt-transport-https
  - software-properties-common
  - wget
  - curl
  - git
  - zsh
  - gnupg
  - gnupg-agent
  - tmux
  - vim
  - unzip
  - fontconfig
  - ca-certificates
  - apt-transport-https
  - rsync
  - make
  - openssh-client
  - build-essential
  - llvm
  - tk-dev
  - xz-utils
  - zlib1g-dev
  - libssl-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - libncurses5-dev
  - libncursesw5-dev
  - libffi-dev
  - liblzma-dev
  - python3-openssl
  - python3-dev
  - shellcheck
  - dnsutils
  - oathtool
  - procps
