# ------ Homebrew Packages ------
brew_cask_packages:
  - firefox
  - google-chrome
  - google-drive
  - iterm2
  - slack
  - spotify
  - visual-studio-code
  - notion
  - keybase
  - discord
  - telegram

brew_packages:
  - curl
  - git
  - unzip
  - gnupg2
  - jq
  - nmap
  - make
  - tmux
  - zsh
  - python
  - bind
  - bat
  - iproute2mac
  - monkeysphere
  - oath-toolkit
  - ripgrep
  - fd
  - coreutils
  - atuin
  - colima
  - snyk/tap/snyk

install_homebrew_if_missing: yes
upgrade_homebrew_packages: yes
